version: '3.8'
services:
  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ./promtail-config:/etc/promtail
    command: --config.file=/etc/promtail/promtail-local-config.yml
    ports:
      - 9080:9080
    networks:
      - promtail
networks:
  promtail:
    driver: bridge