version: "3.8"
services: 
  #==============================================>> MYSQL Database
  mysql: 
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3000:3306"
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQl_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    # Backup Data in db/mysql
        - ./db/mysql:/var/lib/mysql
    networks:
        - mysql
networks:
  mysql:
    driver: bridge

