version: '3.8'
services:
  #=================================================================>> ORACLE DB
  oracle-db:
  # Make sure you have container-registry oracle account
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-db
    environment:
        ORACLE_SID: ${ORACLE_SID}
        # Service Name
        ORACLE_PDB: ${ORACLE_PDB} 
        ORACLE_USER: ${ORACLE_USER}
        ORACLE_PWD: ${ORACLE_PWD}
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - oracle-db
volumes:
  oracle-data:
  oracle-backup:
networks:
  oracle-db:
    driver: bridge