version: '3.8'
services:
#============================================================>> Postgres DB
  postgres:
    image: postgres:12.4-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: mysqladmin ping --protocol=tcp --password=pass --silent
      interval: 5s
      retries: 4
    volumes:
    # Backup Data in pgdata
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
